import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { MovieProvider } from '@/context/MovieContext';
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <body className={inter.className}>
          <MovieProvider>
            <div className="relative w-full flex items-center">
              <Navbar />
            </div>
            {children}
            <Footer />
          </MovieProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
